### ISSUE TITLE
limit.outerReset

### ISSUE THREAD

**Issue by cja1** [StevenThuriot/express-rate-limiter#10]
Hi, I'm getting an error: "error": "\"name\" and \"value\" are required for setHeader()." It's being thrown because limit.outerReset isn't set. Am I missing something / I can't see where outerReset is set in the code.

**Comment by StevenThuriot** [comment]
Seems like I accidentally removed the line during a refactor in commit 1e59419ab79728b95b30336739466713b65b6f01 .

That wasn't supposed to happen and it is really weird I hadn't noticed yet. Thanks for the heads up, will fix asap.

**Comment by StevenThuriot** [comment]
I've added it back and tested the headers, seems to be working again!

I've published a new version on npm (v1.2.0), please let me know if you should encounter any other problems..

**Comment by cja1** [comment]
Thanks - that works now. Appreciate the quick fix.
